// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-1UnuZErSBQd8-vsSPO1IgZvwm3MkFw',
    appId: '1:784163765377:web:33a58cc5a9418d0263a180',
    messagingSenderId: '784163765377',
    projectId: 'chatting-app-79bda',
    authDomain: 'chatting-app-79bda.firebaseapp.com',
    storageBucket: 'chatting-app-79bda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTDGQKKzgVNqIAmQjNAnk3S_rEWQC3wQE',
    appId: '1:784163765377:android:9c688e85a9b8202563a180',
    messagingSenderId: '784163765377',
    projectId: 'chatting-app-79bda',
    storageBucket: 'chatting-app-79bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJZz8tvI9pavMdfhaQEE5FDvhxDTetaZM',
    appId: '1:784163765377:ios:755efba2ded4513e63a180',
    messagingSenderId: '784163765377',
    projectId: 'chatting-app-79bda',
    storageBucket: 'chatting-app-79bda.appspot.com',
    iosBundleId: 'com.example.chatMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJZz8tvI9pavMdfhaQEE5FDvhxDTetaZM',
    appId: '1:784163765377:ios:755efba2ded4513e63a180',
    messagingSenderId: '784163765377',
    projectId: 'chatting-app-79bda',
    storageBucket: 'chatting-app-79bda.appspot.com',
    iosBundleId: 'com.example.chatMobileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx-1UnuZErSBQd8-vsSPO1IgZvwm3MkFw',
    appId: '1:784163765377:web:1d20b8eb0906d3b363a180',
    messagingSenderId: '784163765377',
    projectId: 'chatting-app-79bda',
    authDomain: 'chatting-app-79bda.firebaseapp.com',
    storageBucket: 'chatting-app-79bda.appspot.com',
  );
}
